// Provided module. Do not edit this file.
// This is an ES module. It makes one function available to other files with
// `export default`.
function greeting(name) {
  return 'Hello, ' + name + '!';
}

export default greeting;
