// Provided harness. Do not edit this file.
// It loads your main.js with a dynamic import() and calls the function you
// export as the default, passing in the name 'Ada'. You only edit main.js.
import http from 'http';

let makeWelcome;
try {
  const mod = await import('./main.js');
  makeWelcome = mod.default;
} catch (err) {
  makeWelcome = null;
}

const PORT = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
  const body =
    typeof makeWelcome === 'function'
      ? makeWelcome('Ada')
      : 'main.js did not export a function.';
  res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end(String(body));
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
