// Provided page logic. Do not edit this file. Edit server.js instead.

const emailInput = document.querySelector('#email');
const passwordInput = document.querySelector('#password');
const registerBtn = document.querySelector('#register-btn');
const loginBtn = document.querySelector('#login-btn');
const statusMessage = document.querySelector('#status');
const storedValue = document.querySelector('#stored-value');

async function sendCredentials(url) {
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: emailInput.value.trim(),
      password: passwordInput.value
    })
  });
  const result = await response.json();
  statusMessage.textContent = result.message;
  statusMessage.className = response.ok ? 'ok' : 'error';
  showStoredRecord();
}

async function showStoredRecord() {
  const response = await fetch('/stored-users');
  const users = await response.json();
  const record = users[emailInput.value.trim()];
  if (!record) {
    storedValue.textContent = '(nothing stored for this email yet)';
    return;
  }
  storedValue.textContent = JSON.stringify(record);
}

registerBtn.addEventListener('click', () => sendCredentials('/register'));
loginBtn.addEventListener('click', () => sendCredentials('/login'));
