// Provided page logic. Do not edit this file. Edit server.js instead.

const membersList = document.querySelector('#members-list');
const statusMessage = document.querySelector('#status');

async function loadMembers() {
  try {
    const response = await fetch('/users');
    if (!response.ok) {
      throw new Error('Request failed');
    }
    const users = await response.json();
    membersList.innerHTML = '';
    for (const user of users) {
      const row = document.createElement('tr');

      const idCell = document.createElement('td');
      idCell.textContent = user.id;

      const emailCell = document.createElement('td');
      emailCell.textContent = user.email;

      row.append(idCell, emailCell);
      membersList.append(row);
    }
    statusMessage.textContent = '';
  } catch {
    statusMessage.textContent = 'Could not load members. Is GET /users responding with JSON?';
  }
}

loadMembers();
