// Provided page logic. Do not edit this file. Edit server.js instead.

const authSection = document.querySelector('#auth-section');
const sessionSection = document.querySelector('#session-section');
const emailInput = document.querySelector('#email');
const passwordInput = document.querySelector('#password');
const registerBtn = document.querySelector('#register-btn');
const loginBtn = document.querySelector('#login-btn');
const logoutBtn = document.querySelector('#logout-btn');
const userDisplay = document.querySelector('#user-display');
const statusMessage = document.querySelector('#status');

function showStatus(message, ok) {
  statusMessage.textContent = message;
  statusMessage.className = ok ? 'ok' : 'error';
}

function showLoggedIn(email) {
  userDisplay.textContent = email;
  sessionSection.classList.remove('hidden');
  authSection.classList.add('hidden');
}

function showLoggedOut() {
  sessionSection.classList.add('hidden');
  authSection.classList.remove('hidden');
}

async function sendCredentials(url) {
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: emailInput.value.trim(),
      password: passwordInput.value
    })
  });
  const result = await response.json();
  showStatus(result.message, response.ok);
  if (url === '/login' && response.ok) {
    checkSession();
  }
}

async function checkSession() {
  const response = await fetch('/me');
  if (response.ok) {
    const result = await response.json();
    showLoggedIn(result.email);
  } else {
    showLoggedOut();
  }
}

registerBtn.addEventListener('click', () => sendCredentials('/register'));
loginBtn.addEventListener('click', () => sendCredentials('/login'));

logoutBtn.addEventListener('click', async () => {
  const response = await fetch('/logout', { method: 'POST' });
  const result = await response.json();
  showStatus(result.message, response.ok);
  checkSession();
});

// On page load, ask the server who is logged in. If the session cookie is
// still valid, the page goes straight to the logged-in view.
checkSession();
