// Provided page logic. Do not edit this file. Edit server.js instead.

const playersList = document.querySelector('#players-list');
const statusMessage = document.querySelector('#status');

async function loadPlayers() {
  try {
    const response = await fetch('/players');
    if (!response.ok) {
      throw new Error('Request failed');
    }
    const players = await response.json();
    playersList.innerHTML = '';
    for (const player of players) {
      const li = document.createElement('li');

      const name = document.createElement('span');
      name.className = 'name';
      name.textContent = player.name;

      const score = document.createElement('span');
      score.className = 'score';
      score.dataset.name = player.name;
      score.textContent = player.score;

      const button = document.createElement('button');
      button.textContent = '+1';
      button.dataset.name = player.name;
      button.addEventListener('click', () => addPoint(player.name));

      li.append(name, score, button);
      playersList.append(li);
    }
    statusMessage.textContent = '';
  } catch {
    statusMessage.textContent = 'Could not load players. Is GET /players implemented in server.js?';
  }
}

async function addPoint(name) {
  const response = await fetch('/score', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name })
  });
  if (response.ok) {
    loadPlayers();
  } else {
    statusMessage.textContent = 'Could not update the score. Is POST /score implemented in server.js?';
  }
}

loadPlayers();
