// Browser code for the Account Login page.
// This file is complete and already sends the username and password to your
// POST /login route, then shows the server's answer.
// Do not edit this file; your work is in server.js.

const usernameInput = document.querySelector('#username');
const passwordInput = document.querySelector('#password');
const loginBtn = document.querySelector('#login-btn');
const statusMessage = document.querySelector('#status');

// Send the typed credentials to the server and show the result.
async function logIn() {
  const response = await fetch('/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      username: usernameInput.value.trim(),
      password: passwordInput.value
    })
  });

  let data;
  try {
    data = await response.json();
  } catch {
    data = { message: 'Unexpected response from server' };
  }

  statusMessage.textContent = data.message || '';
  statusMessage.className = response.ok ? 'ok' : 'error';
}

loginBtn.addEventListener('click', logIn);
