// Provided page logic. Do not edit this file. Edit server.js instead.

const postsList = document.querySelector('#posts-list');
const postInput = document.querySelector('#post-input');
const postForm = document.querySelector('#post-form');
const statusMessage = document.querySelector('#status');

async function loadPosts() {
  try {
    const response = await fetch('/posts');
    if (!response.ok) {
      throw new Error('Request failed');
    }
    const posts = await response.json();
    postsList.innerHTML = '';
    for (const text of posts) {
      const li = document.createElement('li');
      li.textContent = text;
      postsList.append(li);
    }
    statusMessage.textContent = posts.length === 0 ? 'No posts yet. Add the first one!' : '';
  } catch {
    statusMessage.textContent = 'Could not load posts. Is GET /posts implemented in server.js?';
  }
}

postForm.addEventListener('submit', async (submitEvent) => {
  submitEvent.preventDefault();
  const text = postInput.value.trim();
  if (!text) {
    return;
  }
  const response = await fetch('/posts', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text })
  });
  if (response.ok) {
    postInput.value = '';
    loadPosts();
  } else {
    statusMessage.textContent = 'Could not save the post. Is POST /posts implemented in server.js?';
  }
});

loadPosts();
