// Provided module. Do not edit this file.
// This file is in the SAME directory as main.js. It exports one function.
function describeMascot(school, mascot) {
  return school + ' teams are the ' + mascot + '.';
}

export default describeMascot;
