// Provided harness. Do not edit this file.
// It loads your main.js with a dynamic import() and serves whatever your file
// exports as its default export, so the tests can read it. You only edit main.js.
import http from 'http';

let result;
try {
  const mod = await import('./main.js');
  result = mod.default;
} catch (err) {
  result = 'Error loading main.js: ' + err.message;
}

const PORT = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
  res.end(String(result));
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
