// Provided page logic. Do not edit this file. Edit server.js instead.

const emailInput = document.querySelector('#email');
const passwordInput = document.querySelector('#password');
const registerBtn = document.querySelector('#register-btn');
const loginBtn = document.querySelector('#login-btn');
const statusMessage = document.querySelector('#status');

async function sendCredentials(url) {
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: emailInput.value.trim(),
      password: passwordInput.value
    })
  });
  const result = await response.json();
  statusMessage.textContent = result.message;
  statusMessage.className = response.ok ? 'ok' : 'error';
}

registerBtn.addEventListener('click', () => sendCredentials('/register'));
loginBtn.addEventListener('click', () => sendCredentials('/login'));
