// Provided harness. Do not edit this file.
// It loads your main.js with a dynamic import() and sends whatever your file
// exports as its default export back as JSON so the tests can read it. You only
// edit main.js.
import http from 'http';

let result;
try {
  const mod = await import('./main.js');
  result = mod.default;
} catch (err) {
  result = { error: err.message };
}

const PORT = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(result));
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
